version: '3.8'

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
  adminer:
    ports:
      - "8080:8080"
  php-fpm:
    environment:
      - PHP_IDE_CONFIG=serverName=app
  postgres:
    environment:
      REPLICATION: 'true'
      WAL_LEVEL: 'logical'
    volumes:
      - ./postgres/datadir:/var/lib/postgresql/data:delegated
